### ISSUE TITLE
Does not stop syncing

### ISSUE THREAD

**Issue by callumgare** [BusterLabs/Partyshare#20] opened 2017-05-22 11:43 UTC
#### Steps to Reproduce
- Downloaded and run (while executable is still in the DMG if that makes any difference)
- OS: macOS Sierra

#### Expected Result
- To leave the "Syncing..." state after a "more or less instantaneous" amount of time.

#### Actual Result
- Gets stuck on "Syncing..."
- [~/Library/Logs/partyshare.busterlabs.xyz/log.log](https://github.com/BusterLabs/Partyshare/files/1018633/log.txt) (ext changed to .txt so github would upload it)

**Comment by jamiew** [comment] 2017-05-22 15:22
Looks like you were probably already running an ipfs daemon? So approximatley a duplicate of #17

**Closed** 2017-05-22 22:31 UTC

**Comment by callumgare** [comment] 2017-05-22 22:33
Yep, you're right. I hadn't actually read the log as I just stuck it up here after a request from the author but going thought it now and combined with the fact that I have the ipfs gateway running as a service on the defaults ports it seems pretty clear that this issue is a dupe.

**Comment by bhstahl** [comment] 2017-05-23 10:32
Thanks for noticing that @jamiew !

**Comment by bhstahl** [comment] 2017-05-25 01:24
@callumgare you should be good to go in the latest release! Thanks for your help
